name: ecommerce
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  #utility
  http: 
  intl:
  logger:
  lottie: ^3.3.1
  url_launcher:
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1
  

  #icons
  cupertino_icons: ^1.0.8
  iconsax:

  #statemgmt
  get:
  get_storage:

  #Product specific
  readmore: ^2.2.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  #Firebase
  firebase_core: ^3.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  assets:
   - assets/logo/
   - assets/icons/categories/
   - assets/icons/payment_methods/
   - assets/images/
   - assets/images/onboarding/
   - assets/images/signup/
   - assets/images/banners/
   - assets/images/products/
   - assets/images/user/


  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-BoldItalic.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-LightItalic.ttf
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400



flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logo/ecommerce_logo_dark.png
  image_dark: assets/logo/ecommerce_logo_light.png
  

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logo/ecommerce_logo_dark.png
    image_dark: assets/logo/ecommerce_logo_light.png

  web: true
    

  
