// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXpu_TsI-Efm2CKRX3JY6WOVsTKkpZXZo',
    appId: '1:799377217080:web:18951840e942112692f8cd',
    messagingSenderId: '799377217080',
    projectId: 'precommerce-a2e82',
    authDomain: 'precommerce-a2e82.firebaseapp.com',
    storageBucket: 'precommerce-a2e82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiIykzC34ktcCx_vE1k1d1-_h-PglTLPQ',
    appId: '1:799377217080:android:9ee3e08b0695031f92f8cd',
    messagingSenderId: '799377217080',
    projectId: 'precommerce-a2e82',
    storageBucket: 'precommerce-a2e82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnR7sB80NOIdNWU0iP5sGx5mVK3MpVnSU',
    appId: '1:799377217080:ios:39386a929c0a85e792f8cd',
    messagingSenderId: '799377217080',
    projectId: 'precommerce-a2e82',
    storageBucket: 'precommerce-a2e82.firebasestorage.app',
    androidClientId: '799377217080-bhk8po5oc70kts939vieq06fofa1d2au.apps.googleusercontent.com',
    iosClientId: '799377217080-21iqq840uh2jku89hrsd41epg4acntg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXpu_TsI-Efm2CKRX3JY6WOVsTKkpZXZo',
    appId: '1:799377217080:web:4f7b9322ff8c9e4f92f8cd',
    messagingSenderId: '799377217080',
    projectId: 'precommerce-a2e82',
    authDomain: 'precommerce-a2e82.firebaseapp.com',
    storageBucket: 'precommerce-a2e82.firebasestorage.app',
  );

}